import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import TextField from '@mui/material/TextField';
import InputAdornment from '@mui/material/InputAdornment';
import IconifyIcon from 'components/base/IconifyIcon';
import { SearchField } from 'design-system';
import { DocSection } from '../../components/DocLayout';
import CodeBlock from '../../components/CodeBlock';
import LivePreview from '../../components/LivePreview';
import SpecTable from '../../components/SpecTable';

const anatomy = [
  [
    <code key="k">InputBase</code>,
    'The box',
    'Border in neutral.darker, theme radius, paper background, 10px padding, letter-spacing 0.5',
  ],
  [
    <code key="k">FilledInput</code>,
    'The variant',
    'Resets the padding MUI applies to the inner input; adds 10px of left padding at size small',
  ],
  [
    <code key="k">TextField</code>,
    'The composition',
    'Wraps FormControl + label + input + helper text, and adds the small elevation shadow',
  ],
  [
    <code key="k">InputAdornment</code>,
    'Icons and units',
    'Secondary colour at h6 size, no margin, 8px of padding on the inner side only',
  ],
];

const sizes = [
  [<code key="k">size=&quot;small&quot;</code>, 'Caption type, 8px / 10px padding', 'Toolbars, filters, dense forms — the default choice'],
  [<code key="k">size=&quot;medium&quot;</code>, 'Subtitle2 type, 10px padding', 'A short standalone form where the field is the focus'],
];

const Controls = () => (
  <DocSection
    id="forms-controls"
    title="Form controls"
    description="Text entry: the field box, its variants, sizes and adornments."
  >
    <Typography variant="body1" paragraph>
      Every text control in the SPA is the same box. <code>InputBase</code> draws it — border,
      radius, background, padding, placeholder colour — and the variant overrides exist mostly to
      get MUI&apos;s own padding out of the way so that box stays intact. That is why{' '}
      <code>filled</code> and <code>outlined</code> look nearly identical here, and why{' '}
      <code>filled</code> is the one to use: the outlined variant also renders a notched fieldset,
      which draws a second border around the first.
    </Typography>

    <SpecTable headers={['Layer', 'Role', 'What it contributes']} rows={anatomy} />

    <Typography variant="h6" gutterBottom>
      The standard field
    </Typography>
    <LivePreview>
      <Stack direction="column" spacing={2.5} maxWidth={360}>
        <TextField variant="filled" size="small" label="E-mail" placeholder="name@school.br" fullWidth />
        <TextField
          variant="filled"
          size="small"
          label="Enrolment code"
          defaultValue="2026-A-0417"
          helperText="Generated by the API — read only"
          slotProps={{ input: { readOnly: true } }}
          fullWidth
        />
        <TextField variant="filled" size="small" label="Archived reason" disabled fullWidth />
      </Stack>
    </LivePreview>
    <CodeBlock
      code={`<TextField
  variant="filled"
  size="small"
  label={t('people.fields.email')}
  placeholder="name@school.br"
  value={form.email}
  onChange={handleChange('email')}
  fullWidth
/>`}
    />

    <Typography variant="h6" gutterBottom>
      Sizes
    </Typography>
    <SpecTable headers={['Size', 'Renders as', 'When']} rows={sizes} />

    <Typography variant="h6" gutterBottom>
      Adornments
    </Typography>
    <Typography variant="body2" color="text.secondary" mb={2}>
      An adornment is part of the field, not a button next to it. Use{' '}
      <code>position=&quot;start&quot;</code> for a symbol that describes the value — a currency, a
      search glyph — and <code>position=&quot;end&quot;</code> for an action on the value, such as
      revealing a password. An interactive adornment is an <code>IconButton</code> and needs an{' '}
      <code>aria-label</code> like any other icon-only control.
    </Typography>
    <LivePreview>
      <Stack direction="column" spacing={2.5} maxWidth={360}>
        <TextField
          variant="filled"
          size="small"
          label="Monthly fee"
          placeholder="0,00"
          fullWidth
          slotProps={{
            input: {
              startAdornment: <InputAdornment position="start">R$</InputAdornment>,
            },
          }}
        />
        <TextField
          variant="filled"
          size="small"
          label="Attachment"
          placeholder="No file selected"
          fullWidth
          slotProps={{
            input: {
              endAdornment: (
                <InputAdornment position="end">
                  <IconifyIcon icon="material-symbols:attach-file" />
                </InputAdornment>
              ),
            },
          }}
        />
      </Stack>
    </LivePreview>
    <CodeBlock
      code={`slotProps={{
  input: {
    startAdornment: <InputAdornment position="start">R$</InputAdornment>,
  },
}}`}
    />

    <Typography variant="h6" gutterBottom>
      Multiline
    </Typography>
    <Typography variant="body2" color="text.secondary" mb={2}>
      Set <code>minRows</code> so the field opens at a useful height and grows with the content.
      Avoid <code>rows</code>, which freezes the height and forces an inner scrollbar on exactly the
      long message the field exists to hold.
    </Typography>
    <LivePreview>
      <TextField
        variant="filled"
        size="small"
        label="Message to guardians"
        multiline
        minRows={3}
        placeholder="Write the announcement…"
        sx={{ maxWidth: 360, width: 1 }}
      />
    </LivePreview>

    <Typography variant="h6" gutterBottom>
      SearchField
    </Typography>
    <Typography variant="body2" color="text.secondary" mb={2}>
      The one text control the design system exports as a pattern. It is a filled, small{' '}
      <code>TextField</code> with the search adornment already attached — use it for the filter row
      above a list rather than rebuilding the same field.
    </Typography>
    <LivePreview>
      <SearchField value="" onChange={() => {}} />
    </LivePreview>

    <Typography variant="h6" gutterBottom>
      Do
    </Typography>
    <ul>
      <li>
        <Typography variant="body2">
          Set the native affordances — <code>type</code>, <code>autoComplete</code>,{' '}
          <code>inputMode</code>. They are free accessibility and free mobile keyboards.
        </Typography>
      </li>
      <li>
        <Typography variant="body2">
          Prefer <code>readOnly</code> over <code>disabled</code> for a value the user may read and
          copy but not change; disabled text is deliberately low contrast.
        </Typography>
      </li>
      <li>
        <Typography variant="body2">
          Keep the field controlled and clear its error the moment the value changes.
        </Typography>
      </li>
    </ul>

    <Typography variant="h6" gutterBottom>
      Don&apos;t
    </Typography>
    <ul>
      <li>
        <Typography variant="body2">
          Use <code>variant=&quot;outlined&quot;</code> or <code>variant=&quot;standard&quot;</code>
          . Outlined draws its notched fieldset around the border <code>InputBase</code> already
          painted, and standard is not styled for this box at all.
        </Typography>
      </li>
      <li>
        <Typography variant="body2">
          Use a placeholder as the label. It vanishes on the first keystroke and is not announced as
          a name by every screen reader.
        </Typography>
      </li>
      <li>
        <Typography variant="body2">
          Format or mask a value as the user types unless the API demands the formatted form —
          normalise on submit instead, and let the server reject what it will not accept.
        </Typography>
      </li>
    </ul>
  </DocSection>
);

export default Controls;
