proxy:
  hosts:
    - scholarpremium.com.br
    - www.scholarpremium.com.br

env:
  clear:
    CORA_API_BASE_URL: https://api.cora.com.br
    CORA_TOKEN_URL: https://matls-clients.api.cora.com.br/token
    CORS_ORIGINS: https://scholarpremium.com.br,https://www.scholarpremium.com.br
    APP_HOST: scholarpremium.com.br

volumes:
  - "scholarpremium_storage:/rails/storage"
